[build]
  publish = "."

# Serve clean URLs by mapping them to .html files
[[redirects]]
  from = "/maternity-gallery"
  to = "/maternity-gallery.html"
  status = 200

[[redirects]]
  from = "/boudoir-gallery"
  to = "/boudoir-gallery.html"
  status = 200

[[redirects]]
  from = "/meet-jelle"
  to = "/meet-jelle.html"
  status = 200

[[redirects]]
  from = "/investment"
  to = "/investment.html"
  status = 200

[[redirects]]
  from = "/fine-art-gallery"
  to = "/fine-art-gallery.html"
  status = 200
